Recipes:
  chestTweak: true
  repeatorTweak: true
  hopperTweak: true
  trappedChestTweak: true
  paperTweak: true
  bookShelfTweak: true
  stringTweak: true
  blazeRodTweak: true
  vineTweak: true
  dirtTweak: true
  bambooTweak: true
  elytraTweak: false
  stickTweak: true
  lanternTweak: true
  quartzTweak: true
  saddleTweak: true
  seapickleTweak: true
