Recipes:
    chestTweak: true
    repeatorTweak: true
    trappedChestTweak: true
    bookShelfTweak: true
    stringTweak: true
    vineTweak: true
    dirtTweak: true
    bambooTweak: true
    elytraTweak: false
    stickTweak: true
    quartzTweak: true
    sadleTweak: true
    seapickleTweak: true
